output_features:
  - name: TripType
    type: category
input_features:
  - name: VisitNumber
    type: numerical
  - name: Weekday
    type: category
  - name: Upc
    type: numerical
  - name: ScanCount
    type: numerical
  - name: FinelineNumber
    type: numerical
combiner:
  type: concat
  num_fc_layers: 3
  fc_size: 128
  dropout: 0.1
training:
  batch_size: 256
  learning_rate: .001
  epochs: 1
  # validation_metric: accuracy
