output_features:
  - name: TripType
    type: category
input_features:
  - name: VisitNumber
    type: numerical
  - name: Weekday
    type: category
  - name: Upc
    type: numerical
  - name: ScanCount
    type: numerical
  - name: FinelineNumber
    type: numerical
combiner:
  type: transformer
  num_layers: 1
  num_heads: 8
  hidden_size: 32
  dropout: 0.1
  fc_dropout: 0.2
  num_fc_layers: 1
training:
  batch_size: 256
  learning_rate: 0.0001
  epochs: 1
