output_features:
  - name: TripType
    type: category
input_features:
  - name: VisitNumber
    type: numerical
  - name: Weekday
    type: category
  - name: Upc
    type: numerical
  - name: ScanCount
    type: numerical
  - name: FinelineNumber
    type: numerical
combiner:
  type: tabnet
  size: 24  # N_a
  output_size: 26  # N_d
  sparsity: 0.000001  # lambda_sparse
  bn_virtual_divider: 8  # factor to divide batch_size B to get B_v from the paper
  bn_momentum: 0.6  # m_B
  num_steps: 5  # N_steps
  relaxation_factor: 1.5  # gamma
  use_keras_batch_norm: false
  bn_virtual_bs: 512  # B_v 
training:
  batch_size: 4096 # B
  eval_batch_size: 4096 # 65536 131072 262144 524288
  epochs: 1
  early_stop: 20
  learning_rate: 0.02
  optimizer:
    type: adam
  decay: true
  decay_steps: 20000
  decay_rate: 0.9
  staircase: true
  regularization_lambda: 1
  validation_field: hand
