output_features:
  - name: torque_1
    type: numerical
input_features:
  - name: position_1
    type: numerical
  - name: position_2
    type: numerical
  - name: position_3
    type: numerical
  - name: position_4
    type: numerical
  - name: position_5
    type: numerical
  - name: position_6
    type: numerical
  - name: position_7
    type: numerical
  - name: velocity_1
    type: numerical
  - name: velocity_2
    type: numerical
  - name: velocity_3
    type: numerical
  - name: velocity_4
    type: numerical
  - name: velocity_5
    type: numerical
  - name: velocity_6
    type: numerical
  - name: velocity_7
    type: numerical
  - name: acceleration_1
    type: numerical
  - name: acceleration_2
    type: numerical
  - name: acceleration_3
    type: numerical
  - name: acceleration_4
    type: numerical
  - name: acceleration_5
    type: numerical
  - name: acceleration_6
    type: numerical
  - name: acceleration_7
    type: numerical
combiner:
  type: tabnet
  size: 128  # N_a
  output_size: 8  # N_d
  sparsity: 0.000001  # lambda_sparse
  bn_momentum: 0.98  # m_B
  num_steps: 4  # N_steps
  relaxation_factor: 1.2  # gamma
  bn_virtual_bs: 4096  # B_v 
training:
  batch_size: 256 # B
  eval_batch_size: 0 # 65536 131072 262144 524288
  epochs: 300
  early_stop: 30 
  learning_rate: 0.00577517
  optimizer:
    type: adam
  decay: true
  decay_steps: 20000
  decay_rate: 0.4
  regularization_lambda: 1
