output_features:
  - column: SalePrice
    name: SalePrice
    type: numerical
input_features:
  - column: MSSubClass
    name: MSSubClass
    type: numerical
  - column: MSZoning
    name: MSZoning
    type: category
  - column: LotFrontage
    name: LotFrontage
    type: numerical
  - column: LotArea
    name: LotArea
    type: numerical
  - column: Street
    name: Street
    type: category
  - column: Alley
    name: Alley
    type: category
  - column: LotShape
    name: LotShape
    type: category
  - column: LandContour
    name: LandContour
    type: category
  - column: Utilities
    name: Utilities
    type: category
  - column: LotConfig
    name: LotConfig
    type: category
  - column: LandSlope
    name: LandSlope
    type: category
  - column: Neighborhood
    name: Neighborhood
    type: category
  - column: Condition1
    name: Condition1
    type: category
  - column: Condition2
    name: Condition2
    type: category
  - column: BldgType
    name: BldgType
    type: category
  - column: HouseStyle
    name: HouseStyle
    type: category
  - column: OverallQual
    name: OverallQual
    type: category
  - column: OverallCond
    name: OverallCond
    type: category
  - column: YearBuilt
    name: YearBuilt
    type: numerical
  - column: YearRemodAdd
    name: YearRemodAdd
    type: numerical
  - column: RoofStyle
    name: RoofStyle
    type: category
  - column: RoofMatl
    name: RoofMatl
    type: category
  - column: Exterior1st
    name: Exterior1st
    type: category
  - column: Exterior2nd
    name: Exterior2nd
    type: category
  - column: MasVnrType
    name: MasVnrType
    type: category
  - column: MasVnrArea
    name: MasVnrArea
    type: numerical
  - column: ExterQual
    name: ExterQual
    type: category
  - column: ExterCond
    name: ExterCond
    type: category
  - column: Foundation
    name: Foundation
    type: category
  - column: BsmtQual
    name: BsmtQual
    type: category
  - column: BsmtCond
    name: BsmtCond
    type: category
  - column: BsmtExposure
    name: BsmtExposure
    type: category
  - column: BsmtFinType1
    name: BsmtFinType1
    type: category
  - column: BsmtFinSF1
    name: BsmtFinSF1
    type: numerical
  - column: BsmtFinType2
    name: BsmtFinType2
    type: category
  - column: BsmtFinSF2
    name: BsmtFinSF2
    type: numerical
  - column: BsmtUnfSF
    name: BsmtUnfSF
    type: numerical
  - column: TotalBsmtSF
    name: TotalBsmtSF
    type: numerical
  - column: Heating
    name: Heating
    type: category
  - column: HeatingQC
    name: HeatingQC
    type: category
  - column: CentralAir
    name: CentralAir
    type: binary
  - column: Electrical
    name: Electrical
    type: category
  - column: 1stFlrSF
    name: 1stFlrSF
    type: numerical
  - column: 2ndFlrSF
    name: 2ndFlrSF
    type: numerical
  - column: LowQualFinSF
    name: LowQualFinSF
    type: numerical
  - column: GrLivArea
    name: GrLivArea
    type: numerical
  - column: BsmtFullBath
    name: BsmtFullBath
    type: numerical
  - column: BsmtHalfBath
    name: BsmtHalfBath
    type: numerical
  - column: FullBath
    name: FullBath
    type: category
  - column: HalfBath
    name: HalfBath
    type: category
  - column: BedroomAbvGr
    name: BedroomAbvGr
    type: numerical
  - column: KitchenAbvGr
    name: KitchenAbvGr
    type: category
  - column: KitchenQual
    name: KitchenQual
    type: category
  - column: TotRmsAbvGrd
    name: TotRmsAbvGrd
    type: category
  - column: Functional
    name: Functional
    type: category
  - column: Fireplaces
    name: Fireplaces
    type: category
  - column: FireplaceQu
    name: FireplaceQu
    type: category
  - column: GarageType
    name: GarageType
    type: category
  - column: GarageYrBlt
    name: GarageYrBlt
    type: numerical
  - column: GarageFinish
    name: GarageFinish
    type: category
  - column: GarageCars
    name: GarageCars
    type: numerical
  - column: GarageArea
    name: GarageArea
    type: numerical
  - column: GarageQual
    name: GarageQual
    type: category
  - column: GarageCond
    name: GarageCond
    type: category
  - column: PavedDrive
    name: PavedDrive
    type: category
  - column: WoodDeckSF
    name: WoodDeckSF
    type: numerical
  - column: OpenPorchSF
    name: OpenPorchSF
    type: numerical
  - column: EnclosedPorch
    name: EnclosedPorch
    type: numerical
  - column: 3SsnPorch
    name: 3SsnPorch
    type: numerical
  - column: ScreenPorch
    name: ScreenPorch
    type: numerical
  - column: PoolArea
    name: PoolArea
    type: numerical
  - column: PoolQC
    name: PoolQC
    type: category
  - column: Fence
    name: Fence
    type: category
  - column: MiscFeature
    name: MiscFeature
    type: category
  - column: MiscVal
    name: MiscVal
    type: numerical
  - column: MoSold
    name: MoSold
    type: category
  - column: YrSold
    name: YrSold
    type: category
  - column: SaleType
    name: SaleType
    type: category
  - column: SaleCondition
    name: SaleCondition
    type: category
combiner:
  type: tabnet
  size: 128  # N_a
  output_size: 8  # N_d
  sparsity: 0.0  # lambda_sparse
  bn_momentum: 0.98  # m_B
  num_steps: 10  # N_steps
  relaxation_factor: 1.0  # gamma
  bn_virtual_bs: 4096  # B_v 
training:
  batch_size: 256 # B
  eval_batch_size: 256 # 65536 131072 262144 524288
  epochs: 300
  early_stop: 30
  learning_rate: 0.00795656
  optimizer:
    type: adam
  decay: true
  decay_steps: 10000
  decay_rate: 0.9
  regularization_lambda: 1
  validation_field: SalePrice
