output_features:
  - name: SalePrice
    type: numerical
input_features:
  - name: MSSubClass
    type: category
  - name: MSZoning
    type: category
  - name: LotFrontage
    type: numerical
  - name: LotArea
    type: numerical
  - name: Street
    type: category
  - name: Alley
    type: category
  - name: LotShape
    type: category
  - name: LandContour
    type: category
  - name: Utilities
    type: category
  - name: LotConfig
    type: category
  - name: LandSlope
    type: category
  - name: Neighborhood
    type: category
  - name: Condition1
    type: category
  - name: Condition2
    type: category
  - name: BldgType
    type: category
  - name: HouseStyle
    type: category
  - name: OverallQual
    type: category
  - name: OverallCond
    type: category
  - name: YearBuilt
    type: numerical
  - name: YearRemodAdd
    type: numerical
  - name: RoofStyle
    type: category
  - name: RoofMatl
    type: category
  - name: Exterior1st
    type: category
  - name: Exterior2nd
    type: category
  - name: MasVnrType
    type: category
  - name: MasVnrArea
    type: numerical
  - name: ExterQual
    type: category
  - name: ExterCond
    type: category
  - name: Foundation
    type: category
  - name: BsmtQual
    type: category
  - name: BsmtCond
    type: category
  - name: BsmtExposure
    type: category
  - name: BsmtFinType1
    type: category
  - name: BsmtFinSF1
    type: numerical
  - name: BsmtFinType2
    type: category
  - name: BsmtFinSF2
    type: numerical
  - name: BsmtUnfSF
    type: numerical
  - name: TotalBsmtSF
    type: numerical
  - name: Heating
    type: category
  - name: HeatingQC
    type: category
  - name: CentralAir
    type: binary
  - name: Electrical
    type: category
  - name: 1stFlrSF
    type: numerical
  - name: 2ndFlrSF
    type: numerical
  - name: LowQualFinSF
    type: numerical
  - name: GrLivArea
    type: numerical
  - name: BsmtFullBath
    type: numerical
  - name: BsmtHalfBath
    type: numerical
  - name: FullBath
    type: numerical
  - name: HalfBath
    type: numerical
  - name: BedroomAbvGr
    type: numerical
  - name: KitchenAbvGr
    type: numerical
  - name: KitchenQual
    type: category
  - name: TotRmsAbvGrd
    type: numerical
  - name: Functional
    type: category
  - name: Fireplaces
    type: numerical
  - name: FireplaceQu
    type: category
  - name: GarageType
    type: category
  - name: GarageYrBlt
    type: numerical
  - name: GarageFinish
    type: category
  - name: GarageCars
    type: numerical
  - name: GarageArea
    type: numerical
  - name: GarageQual
    type: category
  - name: GarageCond
    type: category
  - name: PavedDrive
    type: category
  - name: WoodDeckSF
    type: numerical
  - name: OpenPorchSF
    type: numerical
  - name: EnclosedPorch
    type: numerical
  - name: 3SsnPorch
    type: numerical
  - name: ScreenPorch
    type: numerical
  - name: PoolArea
    type: numerical
  - name: PoolQC
    type: category
  - name: Fence
    type: category
  - name: MiscFeature
    type: category
  - name: MiscVal
    type: numerical
  - name: MoSold
    type: category
  - name: YrSold
    type: numerical
  - name: SaleType
    type: category
  - name: SaleCondition
    type: category
combiner:
  type: tabnet
  size: 128  # N_a
  output_size: 8  # N_d
  sparsity: 0.0  # lambda_sparse
  bn_momentum: 0.98  # m_B
  num_steps: 10  # N_steps
  relaxation_factor: 1.0  # gamma
  bn_virtual_bs: 4096  # B_v 
training:
  batch_size: 256 # B
  eval_batch_size: 256 # 65536 131072 262144 524288
  epochs: 300
  early_stop: 30
  learning_rate: 0.00795656
  optimizer:
    type: adam
  decay: true
  decay_steps: 10000
  decay_rate: 0.9
  regularization_lambda: 1
  validation_field: SalePrice
