output_features:
  - name: Sales
    type: numerical 
input_features:
  - name: Store
    type: category
  - name: DayOfWeek
    type: category
  - name: Customers
    type: numerical
  - name: Open
    type: binary
  - name: Promo
    type: binary
  - name: SchoolHoliday
    type: binary
  - name: StateHoliday
    type: category
  - name: Year
    type: numerical
  - name: Month
    type: category
  - name: Day
    type: category
  - name: CompetitionDistance
    type: numerical
  - name: CompetitionOpenSinceMonth
    type: numerical
  - name: CompetitionOpenSinceYear
    type: numerical
  - name: Promo2
    type: numerical
  - name: Promo2SinceWeek
    type: numerical
  - name: Promo2SinceYear
    type: numerical
combiner:
  type: tabnet
  size: 24  # N_a
  output_size: 26  # N_d
  sparsity: 0.000001  # lambda_sparse
  bn_virtual_divider: 8  # factor to divide batch_size B to get B_v from the paper
  bn_momentum: 0.6  # m_B
  num_steps: 5  # N_steps
  relaxation_factor: 1.5  # gamma
  use_keras_batch_norm: false
  bn_virtual_bs: 512  # B_v 
training:
  batch_size: 4096 # B
  eval_batch_size: 4096 # 65536 131072 262144 524288
  epochs: 1
  early_stop: 20
  learning_rate: 0.02
  optimizer:
    type: adam
  decay: true
  decay_steps: 20000
  decay_rate: 0.9
  staircase: true
  regularization_lambda: 1
