output_features:
  - name: Sales
    type: numerical 
input_features:
  - name: Store
    type: category
  - name: DayOfWeek
    type: category
  - name: Customers
    type: numerical
  - name: Open
    type: binary
  - name: Promo
    type: binary
  - name: SchoolHoliday
    type: binary
  - name: StateHoliday
    type: category
  - name: Year
    type: numerical
  - name: Month
    type: category
  - name: Day
    type: category
  - name: CompetitionDistance
    type: numerical
  - name: CompetitionOpenSinceMonth
    type: numerical
  - name: CompetitionOpenSinceYear
    type: numerical
  - name: Promo2
    type: numerical
  - name: Promo2SinceWeek
    type: numerical
  - name: Promo2SinceYear
    type: numerical
combiner:
  type: concat
  num_fc_layers: 3
  fc_size: 128
  dropout: 0.1
training:
  batch_size: 256
  learning_rate: .001
  epochs: 1
  # validation_metric: accuracy
