input_features:
  - name: Elevation
    type: numerical
  - name: Aspect
    type: numerical
  - name: Slope
    type: numerical
  - name: Horizontal_Distance_To_Hydrology
    type: numerical
  - name: Vertical_Distance_To_Hydrology
    type: numerical
  - name: Horizontal_Distance_To_Roadways
    type: numerical
  - name: Hillshade_9am
    type: numerical
  - name: Hillshade_Noon
    type: numerical
  - name: Hillshade_3pm
    type: numerical
  - name: Horizontal_Distance_To_Fire_Points
    type: numerical
  - name: Wilderness_Area
    type: category
  - name: Soil_Type
    type: category
output_features:
  - name: Cover_Type
    type: category
combiner:
  type: transformer
  num_layers: 1
  num_heads: 8
  hidden_size: 32
  dropout: 0.1
  fc_dropout: 0.2
  num_fc_layers: 1
training:
  batch_size: 256
  learning_rate: 0.0001
  epochs: 1
