output_features:
  - name: isFraud
    type: binary
input_features:
  - name: step
    type: numerical
  - name: type
    type: category
  - name: amount
    type: numerical
  - name: oldbalanceOrg
    type: numerical
  - name: newbalanceOrig
    type: numerical
  - name: oldbalanceDest
    type: numerical
  - name: newbalanceDest
    type: numerical
combiner:
  type: tabnet
  size: 32  # N_a
  output_size: 8  # N_d
  sparsity: 0.0 # lambda_sparse
  bn_momentum: 0.98  # m_B
  num_steps: 3  # N_steps
  relaxation_factor: 1.0  # gamma
  bn_virtual_bs: 256  # B_v 
training:
  batch_size: 256 # B
  eval_batch_size: 256 # 65536 131072 262144 524288
  epochs: 300
  early_stop: 30
  learning_rate: 0.01
  optimizer:
    type: adam
  decay: true
  decay_steps: 2000
  decay_rate: 0.4
  regularization_lambda: 1
  validation_field: isFraud
