output_features:
  - column: target
    name: target
    type: binary
input_features:
  - column: ps_ind_01
    name: ps_ind_01
    type: category
  - column: ps_ind_02_cat
    name: ps_ind_02_cat
    type: number
  - column: ps_ind_03
    name: ps_ind_03
    type: number
  - column: ps_ind_04_cat
    name: ps_ind_04_cat
    type: category
  - column: ps_ind_05_cat
    name: ps_ind_05_cat
    type: category
  - column: ps_ind_06_bin
    name: ps_ind_06_bin
    type: binary
  - column: ps_ind_07_bin
    name: ps_ind_07_bin
    type: binary
  - column: ps_ind_08_bin
    name: ps_ind_08_bin
    type: binary
  - column: ps_ind_09_bin
    name: ps_ind_09_bin
    type: binary
  - column: ps_ind_10_bin
    name: ps_ind_10_bin
    type: binary
  - column: ps_ind_11_bin
    name: ps_ind_11_bin
    type: binary
  - column: ps_ind_12_bin
    name: ps_ind_12_bin
    type: binary
  - column: ps_ind_13_bin
    name: ps_ind_13_bin
    type: binary
  - column: ps_ind_14
    name: ps_ind_14
    type: category
  - column: ps_ind_15
    name: ps_ind_15
    type: category
  - column: ps_ind_16_bin
    name: ps_ind_16_bin
    type: binary
  - column: ps_ind_17_bin
    name: ps_ind_17_bin
    type: binary
  - column: ps_ind_18_bin
    name: ps_ind_18_bin
    type: binary
  - column: ps_reg_01
    name: ps_reg_01
    type: number
  - column: ps_reg_02
    name: ps_reg_02
    type: number
  - column: ps_reg_03
    name: ps_reg_03
    type: number
  - column: ps_car_01_cat
    name: ps_car_01_cat
    type: number
  - column: ps_car_02_cat
    name: ps_car_02_cat
    type: category
  - column: ps_car_03_cat
    name: ps_car_03_cat
    type: category
  - column: ps_car_04_cat
    name: ps_car_04_cat
    type: category
  - column: ps_car_05_cat
    name: ps_car_05_cat
    type: category
  - column: ps_car_06_cat
    name: ps_car_06_cat
    type: category
  - column: ps_car_07_cat
    name: ps_car_07_cat
    type: category
  - column: ps_car_08_cat
    name: ps_car_08_cat
    type: binary
  - column: ps_car_09_cat
    name: ps_car_09_cat
    type: category
  - column: ps_car_10_cat
    name: ps_car_10_cat
    type: category
  - column: ps_car_11_cat
    name: ps_car_11_cat
    type: number
  - column: ps_car_11
    name: ps_car_11
    type: category
  - column: ps_car_12
    name: ps_car_12
    type: number
  - column: ps_car_13
    name: ps_car_13
    type: number
  - column: ps_car_14
    name: ps_car_14
    type: number
  - column: ps_car_15
    name: ps_car_15
    type: number
  - column: ps_calc_01
    name: ps_calc_01
    type: number
  - column: ps_calc_02
    name: ps_calc_02
    type: number
  - column: ps_calc_03
    name: ps_calc_03
    type: number
  - column: ps_calc_04
    name: ps_calc_04
    type: category
  - column: ps_calc_05
    name: ps_calc_05
    type: category
  - column: ps_calc_06
    name: ps_calc_06
    type: category
  - column: ps_calc_07
    name: ps_calc_07
    type: category
  - column: ps_calc_08
    name: ps_calc_08
    type: category
  - column: ps_calc_09
    name: ps_calc_09
    type: category
  - column: ps_calc_10
    name: ps_calc_10
    type: number
  - column: ps_calc_11
    name: ps_calc_11
    type: category
  - column: ps_calc_12
    name: ps_calc_12
    type: category
  - column: ps_calc_13
    name: ps_calc_13
    type: number
  - column: ps_calc_14
    name: ps_calc_14
    type: number
  - column: ps_calc_15_bin
    name: ps_calc_15_bin
    type: binary
  - column: ps_calc_16_bin
    name: ps_calc_16_bin
    type: binary
  - column: ps_calc_17_bin
    name: ps_calc_17_bin
    type: binary
  - column: ps_calc_18_bin
    name: ps_calc_18_bin
    type: binary
  - column: ps_calc_19_bin
    name: ps_calc_19_bin
    type: binary
  - column: ps_calc_20_bin
    name: ps_calc_20_bin
    type: binary
combiner:
  type: tabnet
  size: 32  # N_a
  output_size: 32  # N_d
  sparsity: 0.0001  # lambda_sparse
  bn_momentum: 0.6  # m_B
  num_steps: 5  # N_steps
  relaxation_factor: 1.2  # gamma
  bn_virtual_bs: 1024  # B_v 
trainer:
  batch_size: 1024 # B
  eval_batch_size: 0 # 65536 131072 262144 524288
  epochs: 300
  early_stop: 30
  learning_rate: 0.00172826
  decay: true
  decay_steps: 10000
  decay_rate: 0.9
  validation_field: target
  validation_metric: roc_auc
